config/routes.rb
Rails.application.routes.draw do
   root 'pages#home'
   devise_for :users
   resources :products
  get 'dashboard' => 'pages#dashboard'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
        can :read, :all
       can :manage, Product do |product|
           product.try(:user) == user
       end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
     belongs_to :user 
	   has_attached_file :resource
        has_attached_file :image,
                        :storage => :s3, 
                        :bucket => "devmarketplace",
                        :s3_credentials => {
                        :access_key_id => "AKIAJK5K6CNMVKCXGJYQ",
                        :secret_access_key => "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"
                          } 

  #Pdf
	validates_attachment_content_type :image,
		content_type:  /^image\/(png|gif|jpeg)/,
		message: "Only images allowed"
  #Validação pdf
	validates_attachment_content_type :resource,
		content_type: ['application/pdf'],
		message: "Only pdfs allowed"

  	validates :image, attachment_presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception| 
  	redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if current_user
  		redirect_to products_path
  	end
  end

  def dashboard
          @products = current_user.products
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
      authorize! :manage, @product
  end

  # POST /products
  # POST /products.json
  def create

      @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize! :manage, @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize! :manage, @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :author, :desciption, :price, :availability, :image, :resource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MarketPlace", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">

          <li><%= link_to "Produtos", products_path %></li>

          <% if current_user %>
            
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>

          <% else %>

            <li><%= link_to "Login", new_user_session_path %></li>

          <% end %>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
         <!-- Adicionar -->
  		<% flash.each do |type, message| %>
		  <div class="alert alert-info fade-in">
		 	<button class="close" data-dismiss="alert">X</button>
		 	<%= message %>
		  </div>
		<% end %>

		<div class="container">
			<%= yield %>
		</div>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
	<h1 class="text-center">Dashboard</h1>

	<div class="col-md-4">
		<h3 class="text-center">
		    Produtos <%= link_to "Novo Produto", new_product_path, class: "btn btn-primary btn-sm" %>
		 </h3>

    <!-- Adicionar tabela -->

    		<table class="table table-condensed">
			<thead>

                                         <th>Id</th>
					<th>Nome</th>
					<th>Disponibilidade</th>
					<th></th>
			</thead>
			<tbody>
				<% @products.each do |product| %>
				<tr>
					<td><%= product.id %></td>
					<td><%= product.name %></td>
          <td><%= link_to product.name, product_path(product) %></td>
					<td><%= product.availability %></td>
					<td><%= link_to "Editar", edit_product_path(product) %></td>
					<td></td>
				</tr>
				<% end %>
		 </tbody>
	 </table>

    <!-- Adicionar Tabela -->

	</div>

	<div class="col-md-4">
		<h3 class="text-center">Comprado</h3>
	</div>

	<div class="col-md-4">
		<h3 class="text-center">Vendas</h3>
	</div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<div class="jumbotron">
    <h1>Seja Bem vindo a Nossa Loja</h1>
    <p>Um acervo enorme de itens para você</p>

    <%= link_to "Produtos", products_path, class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
</div>

<div class="row">
  <%= render @products %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: { class: "form-control"} %>
    <%= f.input :author, required: true, label: false, placeholder: "Author", input_html: { class: "form-control"} %>
    <%= f.input :desciption, required: true, label: false, placeholder: "desciption", input_html: { class: "form-control"}, rows: 5 %>
        <br>
    <%= f.input :price, required: true, label: false, placeholder: "price", input_html: { class: "form-control"} %>
        <%= f.input :image %>
       <%= f.input :resource %>

      <div class="checkbox text-center">
     <p>Availability</p>
      <%= f.input :availability, required: false, label: false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
  <div class="col-md-3">
    <div class="thumbnail"> <!-- Criar uma imagem menor -->
       <%= link_to product_path(product) do %>
	         <%= image_tag product.image.url(:original), class: "img-responsive" %> <!-- Adicionado -->
       <% end %>
    </div>
    



     <div class="caption"> 
      <p><strong><%= link_to product.name, product_path(product) %></strong></p>
      <p>R$<%= product.price.to_f / 100 %></p>
    </div>

  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
  <%= render @products %>
</div>

app/views/products/new.html.erb
<h1  class="text-center">New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-6">
      <%= image_tag product.image.url(:original), class: "img-responsive" %>
		</div>

		<div class="col-md-6">
      <h3><%= @product.name %> by <%= @product.author %></h3>
			<p class="justify"><%= @product.desciption %></p>
			<h4 class="text-right">R$<%= @product.price.to_f / 100 %></h4>
		</div>

	</div>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>